# Generated by Django 3.1.5 on 2022-03-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databoxes',
            name='description',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='databoxes',
            name='title',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
