# Generated by Django 3.1.5 on 2022-03-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220321_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='box1',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='box2',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='box3',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='box4',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='box5',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='box6',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='box',
        ),
        migrations.AddField(
            model_name='schedule',
            name='box',
            field=models.ManyToManyField(blank=True, null=True, related_name='box_qst', to='app.dataBoxes'),
        ),
    ]
