# Generated by Django 3.1.5 on 2022-03-21 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_schedule_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxx', to='app.databoxes'),
        ),
    ]
