# Generated by Django 3.1.5 on 2022-03-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_schedule_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='box',
        ),
        migrations.AddField(
            model_name='databoxes',
            name='hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='app.schedule'),
        ),
    ]
